Gabrielmarcelino165/tec 20 listagem de produtos
DesorganizationFiap/tech-challenge pull request #26
Opened 2024-05-15 04:13 UTC by gabriwl165

- [ ] Feature: Load Clientes By Pages/Limit and By `Nome`, `Descricao` e `Preco`
- [ ] Started refactor to put `Clientes` and `Produtos` files inside their own folder, needed to refac all imports

2024-05-15 14:29 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/adapters/produtos/GetProdutoAdapter.java
> +        Predicate<Produto> predicate = produto -> {
Gosto muito de usar predicados para filtrar as listas, no meu ponto de vista, fica muito mais legível o código. E falando de legibilidade: `predicate` não é um bom nome :D.

Principalmente por que na linha 38, você usa `.filter(predicate)...`.

Em termos de legibilidade, um desenvolvedor precisaria ler os critérios do seu `predicate` para entender o que está sendo filtrado. Nessa situação, o mais correto seria a variável `predicate` ter um nome que diz exatamente o que ela faz: `byNomeOrDescricaoOrPreco`. Assim sendo, na linha 38 teríamos uma leitura bem melhor:
`.filter(byNomeOrDescricaoOrPreco)...`.

2024-05-15 14:47 UTC, magneon requested changes
Algumas mudanças necessárias mano, a gente tá utilizando a interface GetProdutosInboundPort ao invés da IGetProdutosUseCase. Alguns testes precisam ser finalizados pois estão comentados e um ajuste maroto no for do CategoriaEnum pra deixar mais semântico.

2024-05-15 14:47 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/adapters/produtos/PostProdutoAdapter.java
> +import org.springframework.stereotype.Component;
Acredito que não estamos mais usando Component, seria interessante dar uma limpada nos imports.

2024-05-15 14:47 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/apis/ClienteController.java
> +
Essa quebra de linha não é necessária, pois os imports são do mesmo tipo. Se fosse um import static, faria sentido.

2024-05-15 14:47 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/domain/model/enums/CategoriaEnum.java
> +        for (CategoriaEnum categoria : CategoriaEnum.values()) {
Aqui podemos simplificar pra tirar esse for:
`Predicate<CategoriaEnum> byId = e -> e.getIdCategoria().equals(id);`
`Arrays.stream(CategoriaEnum.values()).filter(byId).findAny().orElseThrown(() -> new IllegalArgumentException("Invalid codigo: " + id));`

2024-05-15 14:47 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/domain/usecases/produtos/GetProdutosUseCase.java
> +public class GetProdutosUseCase implements IGetProdutosUseCase {
Não estamos criando interfaces do tipo `I**UseCase`, utilizar a interface `GetProdutosInboundPort`

2024-05-15 14:47 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/ports/IGetProdutosUseCase.java
> +public interface IGetProdutosUseCase {
Renomear a interface para `GetProdutosInboundPort` para seguir o padrão já adotado.

2024-05-15 14:47 UTC, magneon commented on src/test/java/br/com/fiap/techchallenge/usecases/clientes/GetClienteUseCaseTest.java
> +package br.com.fiap.techchallenge.usecases.clientes;
> [!CAUTION]
> E os testes dessa classe estão comentados?)

2024-05-16 17:30 UTC, gabriwl165 commented on src/test/java/br/com/fiap/techchallenge/usecases/clientes/GetClienteUseCaseTest.java
> +package br.com.fiap.techchallenge.usecases.clientes;
Sim, esses testes quebraram quando fizeram o refactor na estrutura do projeto, seria necessário abrir uma task separada para essa tarefa

2024-05-16 18:11 UTC, magneon approved these changes

2024-05-16 18:12 UTC, merged