Create controller for get categories
DesorganizationFiap/tech-challenge pull request #30
Opened 2024-05-15 21:44 UTC by Getnerski

2024-05-15 21:54 UTC, magneon requested changes
Alguns ajustes pra ficar de acordo com a arquitetura hexagonal, nada complexo.

2024-05-15 21:54 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/adapters/GetCategoriaAdapter.java
> +@Component
Como se trata de um Adapter e ele fica dentro das camadas do hexagonal, não podemos usar anotações de frameworks.

Aqui, você terá que instanciar o Adapter na Controller, e do Controller passar as dependências do repository e mapper.

2024-05-15 21:54 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/apis/CategoriaController.java
> +    private final GetCategoriaAdapter adapter;
No lugar do GetCategoriaAdapter, você terá duas variáveis de instância:
`private final CategoriaRepository categoriaRepository`;
`private final CategoriaMapper categoriaMapper;`

E na linha 40, passar essas variáveis pro Adapter:
`new GetCategoriaAdapter(categoriaRepository, categoriaMapper);`

2024-05-16 00:06 UTC, Getnerski commented on src/main/java/br/com/fiap/techchallenge/adapters/GetCategoriaAdapter.java
> +@Component
Corrigido

2024-05-16 00:06 UTC, Getnerski commented on src/main/java/br/com/fiap/techchallenge/apis/CategoriaController.java
> +    private final GetCategoriaAdapter adapter;
Corrigido

2024-05-16 02:14 UTC, magneon approved these changes

2024-05-16 02:14 UTC, merged